let alumnos = [
    {
        tipodoc: "CC",
        documento: 1000135417,
        nombres: "Yudi Xiomara",
        apellidos: "Molina Forero",
        genero: "F",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1000990991,
        nombres: "Arleth Duvan",
        apellidos: "Ramirez Vera",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1092157210,
        nombres: "Karla Andrea",
        apellidos: "Loepardi Gomez",
        genero: "F",
        estado: "R",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1000988685,
        nombres: "Geraldine Fabiana",
        apellidos: "Ria�o Vargas",
        genero: "F",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1031642892,
        nombres: "Daniela",
        apellidos: "Navarro Ascencio",
        genero: "F",
        estado: "R",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1026581688,
        nombres: "Diana Mayerly",
        apellidos: "Ahumada Mahecha",
        genero: "F",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1070326569,
        nombres: "Carlos Manuel",
        apellidos: "Mej�a Herrera",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1030697126,
        nombres: "Diego Fernando",
        apellidos: "Guatibonza Erazo",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1000934782,
        nombres: "Laura Alejandra",
        apellidos: "Sandoval Salazar",
        genero: "F",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1011088352,
        nombres: "Nicolas",
        apellidos: "Henao Martinez",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "TI",
        documento: 1028481888,
        nombres: "Thomas Jefrey",
        apellidos: "Rodriguez Ospina",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1034278726,
        nombres: "Natalia",
        apellidos: "Garcia Moreno",
        genero: "F",
        estado: "R",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1013576918,
        nombres: "Daniela Valentina",
        apellidos: "Barrera Oses",
        genero: "F",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1000381531,
        nombres: "Carlos Andres",
        apellidos: "Morales Montes",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1013099099,
        nombres: "Maria Paula",
        apellidos: "Arias Hurtado",
        genero: "F",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1073709068,
        nombres: "Santiago",
        apellidos: "Mejia Bernal",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1073695794,
        nombres: "Nataly",
        apellidos: "Sosa Yara",
        genero: "L",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "TI",
        documento: 1064193348,
        nombres: "Marcos El�as",
        apellidos: "Montes Cruz",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1030697209,
        nombres: "Luis Alberto",
        apellidos: "Martinez Martinez",
        genero: "M",
        estado: "R",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1032511437,
        nombres: "Richard Efrain",
        apellidos: "Marcano Vargas",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1000255735,
        nombres: "Sergio Antonio",
        apellidos: "Morales Zamudio",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1002800495,
        nombres: "Giovany",
        apellidos: "Zuluaga Manrique",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1024473795,
        nombres: "Jeison Alejandro",
        apellidos: "Zambrano Alzate",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1043639243,
        nombres: "Dilan Jose",
        apellidos: "Villa Ramos",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1000129971,
        nombres: "Santiago",
        apellidos: "Henao Ot�lora",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1193549523,
        nombres: "Brayan Steven",
        apellidos: "Ramirez Diaz",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
    {
        tipodoc: "CC",
        documento: 1123800894,
        nombres: "Juan David",
        apellidos: "Hurtado Rodriguez",
        genero: "M",
        estado: "A",
        ciudadnac: "Bogota D.C.",
    },
]
